services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mc-schematic-manager-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
